services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.3.0
    container_name: elasticsearch
    env_file: 
      - .env
    environment:
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
    ports:
      - 9200:9200
    # persist Elasticsearch data
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./certs/ca:/usr/share/elasticsearch/config/certs/ca:ro
      - ./certs/elasticsearch:/usr/share/elasticsearch/config/certs/elasticsearch:ro
    healthcheck:
      test:
      - CMD-SHELL
      - 'curl -s --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} https://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s >/dev/null'
      interval: 30s
      timeout: 35s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana-wolfi:9.3.0
    container_name: kibana
    env_file: 
      - .env
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD="${KIBANA_SYSTEM_PASSWORD}"
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY="${KIBANA_ENCRYPTION_KEY}"
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana/kibana.crt
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana/kibana.key
    volumes:
      - ./certs/ca:/usr/share/kibana/config/certs/ca:ro
      - ./certs/kibana:/usr/share/kibana/config/certs/kibana:ro
    depends_on:
      - elasticsearch
      
  etl:
    build: .
    image: etl_json
    container_name: etl_json
    env_file: 
      - .env
    volumes:
      - ./certs/ca/ca.crt:/certs/ca.crt:ro
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  esdata: