name: Run Unit Tests on Pull Request

on:
  pull_request:
    # Triggers the workflow on 'opened', 'synchronize' (when PR is updated),
    # and 'reopened' events
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run test through makefile
        run: make -f test.mk
        env:
          VERKADA_API_KEY: ${{ secrets.VERKADA_API_KEY }}
